# Generated by Django 4.2.25 on 2025-10-28 11:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday')], max_length=10),
        ),
    ]
